require("jatin.general.base")
require("jatin.general.highlights")
require("jatin.general.maps")
require("jatin.general.plugins")


require("jatin.plugins.autopairs")
require("jatin.plugins.bufferline")
require("jatin.plugins.cmp")
require("jatin.plugins.colorizer")
require("jatin.plugins.git")
require("jatin.plugins.gitsigns")
require("jatin.plugins.lspconfig")
require("jatin.plugins.lspkind")
require("jatin.plugins.lualine")
require("jatin.plugins.lspsaga")
require("jatin.plugins.mason")
require("jatin.plugins.neosolarized")
require("jatin.plugins.null-ls")
require("jatin.plugins.prettier")
require("jatin.plugins.telescope")
require("jatin.plugins.treesitter")
require("jatin.plugins.ts-autotag")
require("jatin.plugins.web-devicons")